export default {
    HeroHeading: "Design Beyond Limits",
    HeroSubheading: "Effortless logo design for businesses, creators, and dreamers alike",
    HeroDescription: "Experience seamless logo creation with Nimbus Arc. Transform ideas into stunning visuals that define your brand in just a few clicks.",
    HeroInputPlaceholder: "An italian pizza restaurant... ",
    createCompStep1Title: "Logo Title",
    createCompStep1Description: "Add your Business, App or Website name for a custom logo.",
    createCompStep2Title: "Describe your Logo",
    createCompStep2Description: "Share your ideas, themes, or inspirations to create a logo that perfectly represents your brand/project.",
    createCompStep3Title: "Choose your Color Palette",
    createCompStep3Description: "Pick the colors that reflect your brands personality and create a lasting impression.",
    createCompStep4Title: "Choose your Design Style",
    createCompStep4Description: "Select the type of logo design that best represents your brands unique identity.",
    createCompStep5Title: "Select your Design Idea",
    createCompStep5Description: "Choose a design style that aligns with your vision, or skip to receive a random suggestion.",
    createCompStep6Title: "Select your plan",
    createCompStep6Description: "Generate unlimited logos with your favourite model!",
    logoGeneratingWaitTitle: "Your logo is being created...",
    logoGeneratingWaitDescription: "✨ Please wait a moment while we work our magic to bring your idea to life.",
    pricingOptions: [
        {
            title: "Free",
            icon: "/assets/free.png",
            features: [
                'Generate Unlimited Logos for free',
                'Longer wait times',
                'Wait time: 30 secs - 3 mins',
                'Limited design options and low quality',
            ],
            button: 'Generate for Free',
        },
        {
            title: "Premium",
            icon: "/assets/thunder.png",
            features: [
                'Generate Unlimited Logos',
                'Shorter wait times',
                'Wait time: < 10 seconds',
                'Get 5 Credits',
            ],
            button: 'Generate for 1 Credit',
        },
    ],
}